### ISSUE TITLE
encountered an error

### ISSUE THREAD

**Issue by BG7UHS** [pentestfunctions/BlueDucky#18]
![Screenshot_20240329-073325_NetHunter_Terminal](https://github.com/pentestfunctions/BlueDucky/assets/25344138/4be7b44f-5323-4f7b-ad23-e580f6980902)

**Comment by pentestfunctions** [comment]
That is due to not downloading all the code. You will need the utils folder that contains the menu_functions.py file.

I'm assuming you are new to python but essentially module not found errors (as you can see on the  last line of your image) is a result of a module or package containing other functions not being installed or accessible.
In this case it can't find the utils folder then the menu_functions file. Which means it cannot load the import functions such as main_menu, read_duckyscript, run, restart_bluetooth_daemon and get_target_address - which are all functions I created for the code to work.

**Comment by BG7UHS** [comment]
I used git clone, the files are complete.
![Screenshot_20240329-211711_NetHunter_Terminal](https://github.com/pentestfunctions/BlueDucky/assets/25344138/5a38d0ec-02ee-43fa-a915-1163a2556573)

**Comment by pentestfunctions** [comment]
You are indeed correct, I can see the utils directory. It might best to make a file in the top level folder called __init__.py just with touch as it can be empty. Just so that other paths you might have don't interfere.

```
touch __init__.py
```

**Comment by BG7UHS** [comment]
Ok 
Can be used normally
